// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sistema_Marcacao_Clinica_Veterinaria.Data;

#nullable disable

namespace Sistema_Marcacao_Clinica_Veterinaria.Migrations
{
    [DbContext(typeof(MarcacaoClinicaVeterinariaDBContext))]
    partial class MarcacaoClinicaVeterinariaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarcacaoServico", b =>
                {
                    b.Property<int>("MarcacoesId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicosId")
                        .HasColumnType("integer");

                    b.HasKey("MarcacoesId", "ServicosId");

                    b.HasIndex("ServicosId");

                    b.ToTable("MarcacaoServico");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EpecieId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<double?>("Peso")
                        .HasColumnType("double precision");

                    b.Property<int?>("ProprietarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EpecieId");

                    b.HasIndex("ProprietarioId");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Municipio")
                        .HasColumnType("text");

                    b.Property<int?>("ProprietarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Rua")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProprietarioId")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Raca")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Marcacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimalID")
                        .HasColumnType("integer");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Ano")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DiaMes")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DiaSemana")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VeterinarioID")
                        .HasColumnType("integer");

                    b.Property<int?>("VeterinarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalID");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("Marcacoes");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.MarcacaoServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MarcacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoPagamento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MarcacaoId");

                    b.HasIndex("ServicoId");

                    b.ToTable("MarcacoesServicos");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Proprietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Proprietarios");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Preco")
                        .HasColumnType("double precision");

                    b.Property<int?>("TipoPagamento")
                        .HasColumnType("integer");

                    b.Property<string>("TipoServico")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Servicos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Servico");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeUsuario")
                        .HasColumnType("text");

                    b.Property<int?>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Veterinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidade")
                        .HasColumnType("text");

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Veterinarios");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Cirurgia", b =>
                {
                    b.HasBaseType("Sistema_Marcacao_Clinica_Veterinaria.Models.Servico");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.ToTable("Servicos", t =>
                        {
                            t.Property("Descricao")
                                .HasColumnName("Cirurgia_Descricao");
                        });

                    b.HasDiscriminator().HasValue("Cirurgia");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Consulta", b =>
                {
                    b.HasBaseType("Sistema_Marcacao_Clinica_Veterinaria.Models.Servico");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.ToTable("Servicos", t =>
                        {
                            t.Property("Descricao")
                                .HasColumnName("Consulta_Descricao");
                        });

                    b.HasDiscriminator().HasValue("Consulta");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Exame", b =>
                {
                    b.HasBaseType("Sistema_Marcacao_Clinica_Veterinaria.Models.Servico");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Exame");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Vacina", b =>
                {
                    b.HasBaseType("Sistema_Marcacao_Clinica_Veterinaria.Models.Servico");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int?>("Periodo")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Vacina");
                });

            modelBuilder.Entity("MarcacaoServico", b =>
                {
                    b.HasOne("Sistema_Marcacao_Clinica_Veterinaria.Models.Marcacao", null)
                        .WithMany()
                        .HasForeignKey("MarcacoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Marcacao_Clinica_Veterinaria.Models.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServicosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Animal", b =>
                {
                    b.HasOne("Sistema_Marcacao_Clinica_Veterinaria.Models.Especie", "Especie")
                        .WithMany("Animais")
                        .HasForeignKey("EpecieId");

                    b.HasOne("Sistema_Marcacao_Clinica_Veterinaria.Models.Proprietario", "Proprietario")
                        .WithMany("Animais")
                        .HasForeignKey("ProprietarioId");

                    b.Navigation("Especie");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Endereco", b =>
                {
                    b.HasOne("Sistema_Marcacao_Clinica_Veterinaria.Models.Proprietario", "Proprietario")
                        .WithOne("Endereco")
                        .HasForeignKey("Sistema_Marcacao_Clinica_Veterinaria.Models.Endereco", "ProprietarioId");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Marcacao", b =>
                {
                    b.HasOne("Sistema_Marcacao_Clinica_Veterinaria.Models.Animal", "Animal")
                        .WithMany("Marcacoes")
                        .HasForeignKey("AnimalID");

                    b.HasOne("Sistema_Marcacao_Clinica_Veterinaria.Models.Veterinario", "Veterinario")
                        .WithMany("Marcacoes")
                        .HasForeignKey("VeterinarioId");

                    b.Navigation("Animal");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.MarcacaoServico", b =>
                {
                    b.HasOne("Sistema_Marcacao_Clinica_Veterinaria.Models.Marcacao", "Marcacao")
                        .WithMany("MarcacoesServicos")
                        .HasForeignKey("MarcacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Marcacao_Clinica_Veterinaria.Models.Servico", "Servico")
                        .WithMany("MarcacoesServicos")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marcacao");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Proprietario", b =>
                {
                    b.HasOne("Sistema_Marcacao_Clinica_Veterinaria.Models.Usuario", "Usuario")
                        .WithOne("Proprietario")
                        .HasForeignKey("Sistema_Marcacao_Clinica_Veterinaria.Models.Proprietario", "UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Veterinario", b =>
                {
                    b.HasOne("Sistema_Marcacao_Clinica_Veterinaria.Models.Usuario", "Usuario")
                        .WithOne("Veterinario")
                        .HasForeignKey("Sistema_Marcacao_Clinica_Veterinaria.Models.Veterinario", "UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Animal", b =>
                {
                    b.Navigation("Marcacoes");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Especie", b =>
                {
                    b.Navigation("Animais");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Marcacao", b =>
                {
                    b.Navigation("MarcacoesServicos");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Proprietario", b =>
                {
                    b.Navigation("Animais");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Servico", b =>
                {
                    b.Navigation("MarcacoesServicos");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Usuario", b =>
                {
                    b.Navigation("Proprietario");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Sistema_Marcacao_Clinica_Veterinaria.Models.Veterinario", b =>
                {
                    b.Navigation("Marcacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
